// react/src/QueryBuilderControl.tsx
import { buttonSmallClass, controlClass, Select as InlaySelect } from '@inlayphp/ui-react'
import { useEffect, useRef, useState } from 'react'
import type { Filter, Option, QueryConstraint, QueryGroup, QueryRule } from './types'

const noValueOperators = new Set(['filled', 'blank', 'is_true', 'is_false', 'has', 'does_not_have'])

export function QueryBuilderControl({ filter, value, onChange }: { filter: Filter; value: unknown; onChange: (value: QueryGroup) => void }) {
  const group = normalizeGroup(value)
  const constraints = filter.constraints ?? []
  const ruleCount = countRules(group)
  return <fieldset className="grid gap-3 rounded-(--inlay-radius) border border-(--inlay-border) bg-(--inlay-surface) p-3" data-slot="query-builder">
    <legend className="px-1 text-sm font-semibold text-(--inlay-text)">{filter.label}</legend>
    <GroupEditor constraints={constraints} depth={1} group={group} maxDepth={filter.maxDepth ?? 5} maxRules={filter.maxRules ?? 50} onChange={onChange} ruleCount={ruleCount} />
  </fieldset>
}

function GroupEditor({ group, constraints, depth, maxDepth, maxRules, ruleCount, onChange }: { group: QueryGroup; constraints: QueryConstraint[]; depth: number; maxDepth: number; maxRules: number; ruleCount: number; onChange: (group: QueryGroup) => void }) {
  const updateChild = (index: number, child: QueryRule | QueryGroup) => onChange({ ...group, children: group.children.map((item, itemIndex) => itemIndex === index ? child : item) })
  const remove = (index: number) => onChange({ ...group, children: group.children.filter((_, itemIndex) => itemIndex !== index) })
  const first = constraints[0]
  return <div className="grid gap-3 border-l-2 border-(--inlay-border) pl-3" data-depth={depth}>
    <div className="flex flex-wrap items-center gap-2"><span className="text-xs font-medium text-(--inlay-muted)">Match</span><InlaySelect ariaLabel={`Group ${depth} boolean`} buttonClassName="text-sm" className="min-w-40" onValueChange={(next) => onChange({ ...group, boolean: next as 'and' | 'or' })} options={[{ value: 'and', label: 'All conditions' }, { value: 'or', label: 'Any condition' }]} value={group.boolean} /></div>
    {group.children.map((child, index) => <div className="flex items-start gap-2" key={index}>
      <div className="min-w-0 flex-1">{'children' in child ? <GroupEditor constraints={constraints} depth={depth + 1} group={child} maxDepth={maxDepth} maxRules={maxRules} onChange={(next) => updateChild(index, next)} ruleCount={ruleCount} /> : <RuleEditor constraints={constraints} onChange={(next) => updateChild(index, next)} rule={child} />}</div>
      <button aria-label="Remove query condition" className={`${buttonSmallClass} border-transparent bg-transparent px-2 text-(--inlay-danger) shadow-none hover:bg-(--inlay-danger-surface)`} onClick={() => remove(index)} type="button">Remove</button>
    </div>)}
    {!group.children.length ? <p className="text-sm text-(--inlay-muted)">No conditions. All records match.</p> : null}
    <div className="flex flex-wrap gap-2"><button className={`${buttonSmallClass} font-medium`} disabled={!first || ruleCount >= maxRules} onClick={() => first && onChange({ ...group, children: [...group.children, { constraint: first.name, operator: first.operators[0], value: '' }] })} type="button">Add condition</button><button className={`${buttonSmallClass} font-medium`} disabled={depth >= maxDepth || ruleCount >= maxRules} onClick={() => onChange({ ...group, children: [...group.children, { boolean: 'and', children: [] }] })} type="button">Add group</button></div>
  </div>
}

function RuleEditor({ rule, constraints, onChange }: { rule: QueryRule; constraints: QueryConstraint[]; onChange: (rule: QueryRule) => void }) {
  const constraint = constraints.find((item) => item.name === rule.constraint || item.relationship === rule.constraint) ?? constraints[0]
  if (!constraint) return null
  const operator = normalizeOperator(rule.operator, constraint)
  // PHP describes every operator, so nothing here infers behaviour from names.
  const definition = constraint.operatorDefinitions?.find((item) => item.name === operator)
  const acceptsMany = definition?.multiple ?? false
  const hasValue = definition ? definition.valueType !== 'none' : !noValueOperators.has(operator)
  const selectOptions = definition?.valueType === 'select' ? (definition.options?.length ? definition.options : constraint.options) : constraint.options
  const inputType = definition?.valueType === 'number' ? 'number' : definition?.valueType === 'date' ? 'date' : 'text'
  return <div className="grid gap-2 md:grid-cols-[minmax(9rem,1fr)_minmax(9rem,1fr)_minmax(10rem,1.5fr)]">
    <InlaySelect ariaLabel="Constraint" buttonClassName="text-sm" className="min-w-0" onValueChange={(next) => { const selected = constraints.find((item) => item.name === next); if (selected) onChange({ constraint: selected.name, operator: selected.operators[0], value: '' }) }} options={constraints.map((item) => ({ value: item.name, label: item.label }))} value={constraint.name} />
    <InlaySelect ariaLabel="Operator" buttonClassName="text-sm" className="min-w-0" onValueChange={(next) => onChange({ ...rule, operator: next, value: '' })} options={constraint.operators.map((item) => ({ value: item, label: constraint.operatorDefinitions?.find((definition) => definition.name === item)?.label ?? operatorLabel(item) }))} value={operator} />
    {hasValue ? constraint.type === 'relationship-constraint' && constraint.remoteOptions && ['is_related_to', 'is_not_related_to'].includes(operator) ? <RemoteRelationshipValue constraint={constraint} multiple={acceptsMany} onChange={(value) => onChange({ ...rule, operator, value })} value={rule.value} /> : definition?.valueType === 'boolean' ? <InlaySelect ariaLabel="Value" buttonClassName="text-sm" className="min-w-0" onValueChange={(next) => onChange({ ...rule, operator, value: next })} options={[{ value: '', label: 'Choose…' }, { value: 'true', label: 'True' }, { value: 'false', label: 'False' }]} value={String(rule.value ?? '')} /> : (definition?.valueType === 'select' || constraint.type === 'select-constraint' || (constraint.type === 'relationship-constraint' && ['is_related_to', 'is_not_related_to'].includes(operator))) ? acceptsMany ? <InlaySelect ariaLabel="Value" buttonClassName="text-sm" className="min-w-0" multiple onValueChange={(next) => onChange({ ...rule, operator, value: next })} options={(selectOptions ?? []).map((option) => ({ value: String(option.value), label: option.label }))} value={Array.isArray(rule.value) ? rule.value.map(String).filter(Boolean) : []} /> : <InlaySelect ariaLabel="Value" buttonClassName="text-sm" className="min-w-0" onValueChange={(next) => onChange({ ...rule, operator, value: next })} options={[{ value: '', label: 'Choose…' }, ...(selectOptions ?? []).map((option) => ({ value: String(option.value), label: option.label }))]} value={String(rule.value ?? '')} /> : <input aria-label="Value" className={controlClass} onChange={(event) => onChange({ ...rule, operator, value: event.target.value })} type={inputType} value={String(rule.value ?? '')} /> : <span className="self-center text-sm text-(--inlay-muted)">No value required</span>}
  </div>
}

function normalizeOperator(operator: string, constraint: QueryConstraint): string {
  if (constraint.operators.includes(operator)) return operator
  const aliases: Record<string, string> = { exists: 'has', not_exists: 'does_not_have', is: 'equals', is_not: 'not_equals' }
  const candidate = aliases[operator]
  return candidate && constraint.operators.includes(candidate) ? candidate : constraint.operators[0] ?? operator
}

function RemoteRelationshipValue({ constraint, value, multiple, onChange }: { constraint: QueryConstraint; value: unknown; multiple: boolean; onChange: (value: string | string[]) => void }) {
  const config = constraint.remoteOptions!
  const [options, setOptions] = useState<Option[]>(constraint.options ?? [])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null)
  const selected = (Array.isArray(value) ? value : [value]).map(item => String(item ?? '')).filter(Boolean)
  const load = async (search = '', values: string[] = []) => {
    if (!config.endpoint) return
    setLoading(true)
    setError(null)
    try {
      const url = new URL(config.endpoint, window.location.href)
      if (search) url.searchParams.set('search', search)
      values.forEach(item => url.searchParams.append('values[]', item))
      const response = await fetch(url, { credentials: 'same-origin', headers: { Accept: 'application/json' } })
      if (!response.ok) throw new Error(`Option request failed with ${response.status}.`)
      const payload = await response.json() as { options?: Option[] }
      const incoming = Array.isArray(payload.options) ? payload.options : []
      setOptions(current => mergeSelectedOptions(current, incoming, selected))
    } catch {
      setError('Related records could not be loaded. Try again.')
    } finally {
      setLoading(false)
    }
  }
  useEffect(() => {
    const missing = selected.filter(item => !options.some(option => String(option.value) === item))
    if (missing.length) void load('', missing)
  }, [])
  useEffect(() => () => { if (timer.current) clearTimeout(timer.current) }, [])
  const search = (term: string) => {
    if (timer.current) clearTimeout(timer.current)
    timer.current = setTimeout(() => { void load(term) }, config.searchDebounce)
  }

  return <div className="grid gap-1.5" data-slot="remote-relationship-select">
    {multiple
      ? <InlaySelect ariaLabel="Value" emptyMessage="No related records found." loading={loading} multiple onSearchChange={search} onValueChange={onChange} options={options} searchable searchAriaLabel="Value" value={selected} />
      : <InlaySelect ariaLabel="Value" emptyMessage="No related records found." loading={loading} onSearchChange={search} onValueChange={onChange} options={options} placeholder="Choose…" searchable searchAriaLabel="Value" value={selected[0] ?? ''} />}
    {error ? <span className="text-xs text-(--inlay-danger)" role="alert">{error}</span> : null}
  </div>
}

function mergeSelectedOptions(current: Option[], incoming: Option[], selected: string[]) {
  const retained = current.filter(option => selected.includes(String(option.value)))
  return [...retained, ...incoming].filter((option, index, all) => all.findIndex(candidate => String(candidate.value) === String(option.value)) === index)
}

function normalizeGroup(value: unknown): QueryGroup { return value && typeof value === 'object' && !Array.isArray(value) && Array.isArray((value as QueryGroup).children) ? value as QueryGroup : { boolean: 'and', children: [] } }
function countRules(group: QueryGroup): number { return group.children.reduce((count, child) => count + ('children' in child ? countRules(child) : 1), 0) }
function operatorLabel(value: string) { return value.split('_').map((part) => part[0].toUpperCase() + part.slice(1)).join(' ') }

// vue/src/QueryBuilderControl.vue
<script setup lang="ts">
import { buttonSmallClass, controlClass } from '@inlayphp/ui'
import { Select as InlaySelect } from '@inlayphp/ui-vue'
import { computed } from 'vue'
import type { Filter, QueryConstraint, QueryGroup, QueryRule } from './types'
import RemoteRelationshipSelect from './RemoteRelationshipSelect.vue'
defineOptions({ name: 'QueryBuilderControl' })
const props = defineProps<{ filter: Filter; value: unknown; depth?: number; root?: boolean }>()
const emit = defineEmits<{ change: [value: QueryGroup] }>()
const group = computed<QueryGroup>(() => props.value && typeof props.value === 'object' && !Array.isArray(props.value) && Array.isArray((props.value as QueryGroup).children) ? props.value as QueryGroup : { boolean: 'and', children: [] })
const constraints = computed(() => props.filter.constraints ?? [])
const currentDepth = computed(() => props.depth ?? 1)
// Keep query-builder controls on the same border/focus/theme contract as the
// table search and filter controls (and the React adapter).
const control = `${controlClass} text-sm`
const noValue = new Set(['filled', 'blank', 'is_true', 'is_false', 'has', 'does_not_have'])
const booleanOptions = [{ value: 'and', label: 'All conditions' }, { value: 'or', label: 'Any condition' }]
function isGroup(child: QueryRule | QueryGroup): child is QueryGroup { return 'children' in child }
function updateChild(index: number, child: QueryRule | QueryGroup) { emit('change', { ...group.value, children: group.value.children.map((item, itemIndex) => itemIndex === index ? child : item) }) }
function remove(index: number) { emit('change', { ...group.value, children: group.value.children.filter((_, itemIndex) => itemIndex !== index) }) }
function addRule() { const first = constraints.value[0]; if (first) emit('change', { ...group.value, children: [...group.value.children, { constraint: first.name, operator: first.operators[0], value: '' }] }) }
function addGroup() { emit('change', { ...group.value, children: [...group.value.children, { boolean: 'and', children: [] }] }) }
function constraintFor(rule: QueryRule) { return constraints.value.find((item) => item.name === rule.constraint || item.relationship === rule.constraint) ?? constraints.value[0] }
function normalizeOperator(rule: QueryRule, constraint = constraintFor(rule)) {
  if (!constraint) return rule.operator
  if (constraint.operators.includes(rule.operator)) return rule.operator
  const aliases: Record<string, string> = { exists: 'has', not_exists: 'does_not_have', is: 'equals', is_not: 'not_equals' }
  const candidate = aliases[rule.operator]
  return candidate && constraint.operators.includes(candidate) ? candidate : constraint.operators[0] ?? rule.operator
}
function operatorFor(rule: QueryRule) { const constraint = constraintFor(rule); return constraint?.operatorDefinitions?.find(item => item.name === normalizeOperator(rule, constraint)) }
function changeConstraint(rule: QueryRule, name: string) { const next = constraints.value.find((item) => item.name === name)!; return { constraint: next.name, operator: next.operators[0], value: '' } }
function singleValue(value: string | string[]) { return Array.isArray(value) ? value[0] ?? '' : value }
// PHP describes every operator, so nothing here infers behaviour from names.
function acceptsMany(constraint: QueryConstraint, operator: string) { return constraint.operatorDefinitions?.find(item => item.name === operator)?.multiple ?? false }
function selectValue(rule: QueryRule, constraint: QueryConstraint) { return acceptsMany(constraint, rule.operator) ? (Array.isArray(rule.value) ? rule.value.map(String).filter(Boolean) : []) : String(rule.value ?? '') }
function hasValue(rule: QueryRule) { const operator = normalizeOperator(rule); return operatorFor(rule)?.valueType !== 'none' && !noValue.has(operator) }
function isSelect(rule: QueryRule) { return operatorFor(rule)?.valueType === 'select' }
function optionsFor(rule: QueryRule) { const options = operatorFor(rule)?.options; return options?.length ? options : constraintFor(rule)?.options }
function inputType(rule: QueryRule) { const definition = operatorFor(rule); return definition?.valueType === 'number' ? 'number' : definition?.valueType === 'date' ? 'date' : 'text' }
function operatorLabel(constraint: QueryConstraint, operator: string) { return constraint.operatorDefinitions?.find(item => item.name === operator)?.label ?? label(operator) }
function countRules(value: QueryGroup): number { return value.children.reduce((count, child) => count + (isGroup(child) ? countRules(child) : 1), 0) }
function label(value: string) { return value.split('_').map(part => part[0].toUpperCase() + part.slice(1)).join(' ') }
</script>

<template>
  <fieldset :class="root === false ? 'grid gap-3' : 'grid gap-3 rounded-(--inlay-radius) border border-(--inlay-border) bg-(--inlay-surface) p-3'" data-slot="query-builder">
    <legend v-if="root !== false" class="px-1 text-sm font-semibold text-(--inlay-text)">{{ filter.label }}</legend>
    <div class="grid gap-3 border-l-2 border-(--inlay-border) pl-3" :data-depth="currentDepth">
      <div class="flex flex-wrap items-center gap-2"><span class="text-xs font-medium text-(--inlay-muted)">Match</span><InlaySelect :aria-label="`Group ${currentDepth} boolean`" button-class-name="text-sm" class-name="min-w-40" :model-value="group.boolean" :options="booleanOptions" @update:model-value="value => emit('change', { ...group, boolean: singleValue(value) as 'and' | 'or' })" /></div>
      <div v-for="(child, index) in group.children" :key="index" class="flex items-start gap-2">
        <div class="min-w-0 flex-1">
          <QueryBuilderControl v-if="isGroup(child)" :depth="currentDepth + 1" :filter="filter" :root="false" :value="child" @change="updateChild(index, $event)" />
          <div v-else-if="constraintFor(child)" class="grid gap-2 md:grid-cols-[minmax(9rem,1fr)_minmax(9rem,1fr)_minmax(10rem,1.5fr)]">
            <InlaySelect aria-label="Constraint" button-class-name="text-sm" class-name="min-w-0" :model-value="constraintFor(child)!.name" :options="constraints.map(item => ({ value: item.name, label: item.label }))" @update:model-value="value => updateChild(index, changeConstraint(child, singleValue(value)))" />
            <InlaySelect aria-label="Operator" button-class-name="text-sm" class-name="min-w-0" :model-value="normalizeOperator(child)" :options="constraintFor(child)!.operators.map(operator => ({ value: operator, label: operatorLabel(constraintFor(child)!, operator) }))" @update:model-value="value => updateChild(index, { ...child, operator: singleValue(value), value: '' })" />
            <RemoteRelationshipSelect v-if="hasValue(child) && constraintFor(child)!.type === 'relationship-constraint' && constraintFor(child)!.remoteOptions && ['is_related_to', 'is_not_related_to'].includes(normalizeOperator(child))" :constraint="constraintFor(child)!" :control-class="control" :multiple="acceptsMany(constraintFor(child)!, normalizeOperator(child))" :value="child.value" @change="updateChild(index, { ...child, value: $event })" />
            <InlaySelect v-else-if="hasValue(child) && operatorFor(child)?.valueType === 'boolean'" aria-label="Value" button-class-name="text-sm" class-name="min-w-0" :model-value="String(child.value ?? '')" :options="[{ value: '', label: 'Choose…' }, { value: 'true', label: 'True' }, { value: 'false', label: 'False' }]" @update:model-value="value => updateChild(index, { ...child, value: singleValue(value) })" />
            <template v-else-if="hasValue(child) && isSelect(child)"><InlaySelect v-if="acceptsMany(constraintFor(child)!, normalizeOperator(child))" aria-label="Value" button-class-name="text-sm" class-name="min-w-0" multiple :model-value="selectValue({ ...child, operator: normalizeOperator(child) }, constraintFor(child)!)" :options="(optionsFor(child) ?? []).map(option => ({ value: String(option.value), label: option.label }))" @update:model-value="value => updateChild(index, { ...child, value })" /><InlaySelect v-else aria-label="Value" button-class-name="text-sm" class-name="min-w-0" :model-value="selectValue({ ...child, operator: normalizeOperator(child) }, constraintFor(child)!)" :options="[{ value: '', label: 'Choose…' }, ...(optionsFor(child) ?? []).map(option => ({ value: String(option.value), label: option.label }))]" @update:model-value="value => updateChild(index, { ...child, value: singleValue(value) })" /></template>
            <input v-else-if="hasValue(child)" aria-label="Value" :class="control" :type="inputType(child)" :value="String(child.value ?? '')" @input="updateChild(index, { ...child, value: ($event.target as HTMLInputElement).value })" />
            <span v-else class="self-center text-sm text-(--inlay-muted)">No value required</span>
          </div>
        </div>
        <button aria-label="Remove query condition" :class="`${buttonSmallClass} border-transparent bg-transparent px-2 text-(--inlay-danger) shadow-none hover:bg-(--inlay-hover)`" type="button" @click="remove(index)">Remove</button>
      </div>
      <p v-if="!group.children.length" class="text-sm text-(--inlay-muted)">No conditions. All records match.</p>
      <div class="flex flex-wrap gap-2"><button :class="`${buttonSmallClass} font-medium`" :disabled="!constraints.length || countRules(group) >= (filter.maxRules ?? 50)" type="button" @click="addRule">Add condition</button><button :class="`${buttonSmallClass} font-medium`" :disabled="currentDepth >= (filter.maxDepth ?? 5) || countRules(group) >= (filter.maxRules ?? 50)" type="button" @click="addGroup">Add group</button></div>
    </div>
  </fieldset>
</template>
